### ISSUE TITLE
Setting input icon to false leaves empty space

### ISSUE THREAD

**Issue by henritoivar** [unmade/am-date-picker#12]
First of all thanks for creating an alternative to the current angular material datepicker. If a few things minor things would be different i would very happily use this as a replacement.

The issue:
Setting am-show-input-icon to false hides the icon but leaves padding/empty space.
This looks off when you have other elements in your form that do not have an icon. Also the default behavior for angular material form elements is that removing an icon does not leave empty space.

Also it would be nice if the clicking on the icon would open the datepicker dialog.

**Comment by unmade** [comment]
Thank you! 
It surely shouldn't leave padding. The problem is, when md-input-container has md-icon inside, it automatically adds class `has-icon` which results in padding. I try to solve it.

**Comment by unmade** [comment]
Finally I have found time to solve this problem. Input icon doesn't leave empty space now.
