### ISSUE TITLE
How to use ng-message with the directive?

### ISSUE THREAD

**Issue by henritoivar** [unmade/am-date-picker#13]
In angular material the input element and ng-messages are wrapped with md-input-container to show error messages properly. As the md-input-container is already included in the directive i can't see a way to include the ng-messages part in there.

What would be the correct way to show an error message?

**Comment by unmade** [comment]
I don't think there is a proper way to show error messages for now. I take a look at it, and try to implement similar solution to what `md-datepicker` offers. By the way, which attributes do you want to support `ngMessages`? I think about `min-date`, `max-date`, `required` and `valid`.

**Comment by henritoivar** [comment]
Thanks. In my case i only needed required, but min-date, max-date and valid seem also reasonable.

**Comment by unmade** [comment]
I've added support for ngMesages. If you think the problem solved, please close the issue.

**Comment by henritoivar** [comment]
Thank you!
