### ISSUE TITLE
How do I create custom message error with angular formly??

### ISSUE THREAD

**Issue by khanhdd123** [unmade/am-date-picker#15]
In formly file I have following code
{
        key : 'test2',
        type : 'datepicker',
        templateOptions : {
          label : 'DAAA'
        },
        validation: {
          messages: {
            required: function(viewValue, modelValue, scope) {
              return scope.to.label + ' is required'
            }
          }
        }
      }

Now I create amdatepicker like this
<am-date-picker 
                ng-model="model[options.key]"
                am-input-date-format="L"
                am-input-label="{{options.templateOptions.label}}"
                am-max-date="maxDate"
                am-max-year="2015"
                am-min-date="minDate"
                am-min-year="2000"
                am-popup-date-format="D/M"
                am-today-button="Today"
                am-show-input-icon="true"
                am-locale ="vi"
                required
                >
</am-date-picker>

<div ng-if="options.validation.errorExistsAndShouldBeVisible" ng-messages="options.formControl.$error"><div ng-message="{{::name}}" ng-repeat="(name, message) in ::options.validation.messages">{{message(options.formControl.$viewValue, options.formControl.$modelValue, this)}}</div></div>

I can't use ng-if="options.validation.errorExistsAndShouldBeVisible".
Anybody help me??

**Comment by unmade** [comment]
Could you post a codepen, please? I've never worked with angular-formly before. 

By the way, now `am-date-picker` supports `ng-messages`.  Supported attributes are:
- `required`: whether a required date is not set.
- `minDate`: whether the selected date is before the minimum allowed date.
- `maxDate`: whether the selected date is after the maximum allowed date.
- `valid`: whether the specified is not valid date.

**Comment by khanhdd123** [comment]
Can I custom validation in amdatepicker??
Example when I pick a date,it will show an error if I pick a date - current date > 10 year??

**Comment by unmade** [comment]
Yes, you can do custom validation with ng-messages.
Since angular 1.3 you could add your own validation rules. You could read more [here](http://odetocode.com/blogs/scott/archive/2014/10/16/working-with-validators-and-messages-in-angularjs.aspx).

If I understand you correctly, you want to show error message if picked date is greater more than ten years from current date. One of the way to do it:
- Create directive:

``` js
directive("myRule", function() {
      return {
          restrict: "A",
          require: "ngModel",
          link: function(scope, element, attributes, ngModel) {
              ngModel.$validators.myRule = function(modelValue) { 
                  return modelValue.getUTCFullYear() - new Date().getUTCFullYear() < 10;
              }
          }
      };
```
- Apply the validation rule

``` html
<form name="myForm">
  <am-date-picker ng-model="date" myRule> </am-date-picker>
    <div ng-messages="myForm.dateField.$error" class="validation-messages">
      <div ng-message="myRule">It's more than 10 years!</div>
  </div>
</form>
```

**Comment by khanhdd123** [comment]
I want when I pick a date,then I delete this in input field,then show error??In angular formly has ng-if = "options.validation.errorExistsAndShouldBeVisible" but not working?? You can explain for me??

**Comment by khanhdd123** [comment]
The way you create message always show message error when I load my project for the first time.My problem is only show error if user pick a date then delete this by close button.

**Comment by unmade** [comment]
I've never worked with angular-formly before, so I can't explain why it doesn't work for you.
As I wrote earlier, if you posted a codepen/jsfiddle/etc it would be easier to understand what's happening.

You could init date with `null` value. After clicking clear button the date value will be set to the `undefined`. With that in mind you could use condition to show/hide error message:

``` html
<form name="myForm">
  <am-date-picker ng-model="date" required> </am-date-picker>
    <div ng-messages="myForm.dateField.$error" ng-if="date === undefined">
      <div ng-message="required">The date is required</div>
  </div>
</form>
```

In that case, the error message will be shown only when user picks a date and then clears it.

**Comment by khanhdd123** [comment]
Oh,can you show me in codepen or something?? I will show you my problem in codepen soon.
Thank.

**Comment by khanhdd123** [comment]
Now you can see my code in codepen.Please check my problem and give me an ansewer.
http://codepen.io/duykhanhbkk57/pen/GZvZvm

**Comment by unmade** [comment]
Yeah, I've fixed it. The problem was in $touched value. The `errorExistsAndShouldBeVisible` uses condition `field invalid && (field touched || validation.show)`, but $touched value never triggered.

Check out your codepen again.

**Comment by khanhdd123** [comment]
Yeah,thank a lot.

**Comment by khanhdd123** [comment]
Seem like you have been modify in am-date-picker.min.js.How can I format date in model to L in moment.js??
You can see in codepen

**Comment by unmade** [comment]
If you need it only in html, here is one of the way:

``` js
model = {
  moment: moment
};
```

``` html
<pre>{{ vm.model.moment(vm.model.date).format('L') }}</pre>
```

Other way is to use `ng-change` attribute.

**Comment by khanhdd123** [comment]
OK thank a lot.You've created the most of date picker I've ever seen before.

**Comment by khanhdd123** [comment]
So,how to i need modify it on am-date-picker.min.js file??

**Comment by unmade** [comment]
Thank you!

If you want to modify the build by yourself, here is [instruction](https://github.com/unmade/am-date-picker/tree/master/demo).
