### ISSUE TITLE
Input icon overflows input label

### ISSUE THREAD

**Issue by ghost** [unmade/am-date-picker#16]
Hi,

and thanks for great datepicker!

I integrated it to my app and noticed two little issues. 
1. I have `am-show-input-icon="true"` in my html. The issue is that Input icon is placed over beginning of input field and input label is below the icon. How to place icon in the front of the input field?
2. I have changed the background color of `am-date-picker__month-year` -div to dark and foreground color white in my am-date-picker.html and it works fine. Only issue is that the color of chevron icons remain dark. I have edited css-file: `.am-date-picker__chevron {color: white;}`, but no success. So how to change icon color to white?

Best regards

**Comment by unmade** [comment]
Hello,

Thank you for giving my datepicker a chance.

First of all, which version of am-date-picker and angular-material are you using?
Angular-material changes logic of placing md-icon in md-input-container from version to version, so I'm working on the solution how to fix it. So far it seems to work correct with angular-material 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.6.

I've made a [codepen](http://codepen.io/fdooch/pen/YqVjqj) with applied css styles.

**Comment by ghost** [comment]
Hi, and thanks for answering!

I cloned your master branch yesterday so am-date-picker is latest version. My angular-material version is v1.1.0-rc1. I just copied content of src folder to my app repository and built it along with my gulp tasks. 

I tried those lines in your codepen, but no success.. weird.. I use scss instead of less.

**Comment by ghost** [comment]
Installed 1.0.6 and yep, it's working now, thanks!

But css issue remains..

**Comment by ghost** [comment]
Hi again,

Found solution for css issue: `.am-date-picker__chevron {fill: white;}`

Best regards
