### ISSUE TITLE
Cannot find moment library

### ISSUE THREAD

**Issue by BkSouX** [unmade/am-date-picker#20]
Hello, 

I have an issue integrating your library with npm like this in package.json :
`"angular-material-datepicker": "unmade/am-date-picker"` 

I import the library in my project like this : 
`import 'angular-material-datepicker/dist/am-date-picker.min';`

I already have moment library in my package.json.

And when i navigate on the page integrating am-date-picker, here the error i take when clicking on the generated input : 
`ReferenceError: moment is not defined`

Do you know what could be the problem ? 

Thanks,
Bruno

**Comment by unmade** [comment]
Hello Bruno!

I guess you are using TypeScript, aren't you? Unfortunately, I'm not familiar with this language.
This date picker uses moment.js library as a dependency, so make sure you have all dependencies install and imported. Maybe that could help.

**Comment by BkSouX** [comment]
Hi,

I'm using ES6 with babel and Webpack.
I have to include that plugin in my webpack configuration : 

```
    new webpack.ProvidePlugin({
      moment: 'moment'
    }),
```

Everything's working now ;)

Bruno
