### ISSUE TITLE
Suggestion: month view

### ISSUE THREAD

**Issue by j-tegen** [unmade/am-date-picker#4]
First of all, really nice looking directive. It would be really nice with some kind of month view (think something like: https://eonasdan.github.io/bootstrap-datetimepicker/). If this would to be added, a nice additional feature would be to be able to pick your pick scope, i.e. if you want to pick dates down to specific days, months or only years.

**Comment by unmade** [comment]
I thought about it, but didn't come up with a solution how it should look like, particularly how to switch between days/months/years selection should look like. In [bootstrap-datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker/) is a little different approach, that doesn't fit material specs.
