### ISSUE TITLE
Date picker service

### ISSUE THREAD

**Issue by SirDarquan** [unmade/am-date-picker#5]
In my code, all dialog boxes are closed when the browser back button is pressed but the browser doesn't leave the current page. Not everyone requires this functionality and I wouldn't ask you to add it into you code just for me. But the way I'm able to achieve this because the Material Design dialogs are opened using a service that returns a promise. If you could make a service for your date picker that could handle opening and closing the picker dialog similar to the mdDialog service, it would solve quite a few problems I have like wanting the calendar icon to be in a different place and clickable on desktop and having the input box be directly editable. It should also allow me to dynamically update the locale and text because my application allows my users to do so, and I'd need the picker to match settings.

**Comment by unmade** [comment]
Sorry, I don't have time for this. You could try it by yourself. I also use $mdDialog to open picker.
